In [1]:
import pandas as pd
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [2]:
insurance_data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Supervised Learning/00_starting_ML/insurance.csv")

In [3]:
insurance_data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
X2 = insurance_data.drop(columns = ["charges"])
y2= insurance_data["charges"]

X2 = pd.get_dummies(X2,columns=["region"],drop_first=False)

X2["sex"] = X2["sex"].map({"female":1 ,"male":0})
X2["smoker"] = X2["smoker"].map({"yes":1 ,"no":0})

X2["age_smoker"] = X2["age"] * X2["smoker"]
X2["bmi_smoker"] = X2["bmi"] * X2["smoker"]

X2_train, X2_test, y2_train, y2_test = train_test_split(
    X2, y2, test_size=0.2, random_state=42)

X2.head()

,age,sex,bmi,children,smoker,region_northeast,region_northwest,region_southeast,region_southwest,age_smoker,bmi_smoker
0,19,1,27.900,0,1,False,False,False,True,19,27.9
1,18,0,33.770,1,0,False,False,True,False,0,0.0
2,28,0,33.000,3,0,False,False,True,False,0,0.0
3,33,0,22.705,0,0,False,True,False,False,0,0.0
4,32,0,28.880,0,0,False,True,False,False,0,0.0

In [5]:
lasso_model = Lasso(alpha=0.5)
lasso_model.fit(X2_train, y2_train)

Lasso(alpha=0.5)

In [6]:
# predict value

y2_pred = lasso_model.predict(X2_test)

In [7]:
mse = mean_squared_error(y2_test, y2_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 20919120.690722693

# LASSO-CV

### find best alpha for model

In [11]:
from sklearn.linear_model import LassoCV

a = [0.001 ,0.1 ,1 , 2, 5,10,20,30,40,50,100]

lasso_cv_model = LassoCV(
    alphas = a,
    cv = 5,
    max_iter = 1000,
    random_state = 42
)

lasso_cv_model.fit(X2_train,y2_train)

print("best aplha for lasso : ", lasso_cv_model.alpha_)

y2_pred = lasso_cv_model.predict(X2_test)

mse = mean_squared_error(y2_test, y2_pred)
print("Mean Squared Error:", mse)

best aplha for lasso :  0.001
Mean Squared Error: 20922596.5280062

# Note :

### Ridge Regression is work same like lasso