In [1]:
import pandas as pd

In [2]:
ser = pd.Series([1,2,3,4,5,6,7,8,9,0])

print(ser)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9    0
dtype: int64

In [3]:
ser

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9    0
dtype: int64

# Labelling

In [4]:
print(ser[1])

2

In [8]:
ser2 = pd.Series([1,2,3,4,5,6] , index = ["a","b","c","x","y","z"])

In [6]:
ser2

a    1
b    2
c    3
x    4
y    5
z    6
dtype: int64

In [10]:
print(ser2["x"])

4

# Series Properties

In [11]:
# homogenous (all data are same type)
ser3= pd.Series([1,2,3,4,5,6,"w"] , index = ["a","b","c","x","y","z",2])
ser3

# dtype is now object

a    1
b    2
c    3
x    4
y    5
z    6
2    w
dtype: object

In [12]:
# vectorization
ser4 = pd.Series([1,2,3,4,5,6])
ser5 = pd.Series([1,2,3,4,5,6])

print(ser4 + ser5)

0     2
1     4
2     6
3     8
4    10
5    12
dtype: int64

In [14]:
# handle missing values with NAN

# have muatble value , immutable size
ser6 = pd.Series([1,2,3,4,5,6])

ser6[4] = 100

ser6

0      1
1      2
2      3
3      4
4    100
5      6
dtype: int64