In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Pandas/employee_data.csv")

df

# Methods Of Dataframe :

In [ ]:
# head() : print first 5 rows
# head(n) : print first n rows

df.head()

In [ ]:
# tail() : print last 5 rows
# tail(n) : print last n rows

df.tail()

In [ ]:
# sample() : print random 1 rows
# sample(n) : print random n rows

df.sample()

In [19]:
# info() : give summary information about DF

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [21]:
# shape() : give (no. of rows , no. of column)
#  this is tuple , so it not a calleble like function

df.shape

(10, 5)

In [23]:
# describe() : give detailed description of numeric value columns

df.describe()

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [24]:
# columns : list all columns name

df.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

In [25]:
# nunique() : number of unique elements in each columns

df.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64