In [1]:
import pandas as pd

In [4]:
df1 = pd.DataFrame({
    "id" : [1,2],
    "name" : ["mit" , "kavy"]
})

df2 = pd.DataFrame({
    "id" : [1,2],
    "name" : ["dev" , "kishan"]
})

In [6]:
df1

   id  name
0   1   mit
1   2  kavy

In [7]:
df2

   id    name
0   1     dev
1   2  kishan

In [8]:
pd.concat([df1 , df2])

   id    name
0   1     mit
1   2    kavy
0   1     dev
1   2  kishan

In [9]:
pd.concat([df2,df1])

   id    name
0   1     dev
1   2  kishan
0   1     mit
1   2    kavy

In [11]:
# make new label , not copy of index of parent table
pd.concat([df1,df2] , ignore_index=True)

   id    name
0   1     mit
1   2    kavy
2   1     dev
3   2  kishan

In [12]:
pd.concat([df1,df2] , axis=1)

   id  name  id    name
0   1   mit   1     dev
1   2  kavy   2  kishan