In [64]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [65]:
df = pd.read_csv("/content/drive/MyDrive/Machine Learning/Supervised Learning/extra_practice_task/email_detection/spam.csv")
df2 = pd.read_csv("/content/drive/MyDrive/Machine Learning/Supervised Learning/extra_practice_task/email_detection/Phishing_Email.csv")

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

# for DF

In [67]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [68]:
df.shape

(5572, 2)

In [69]:
print(df['Category'].value_counts())

Category
ham     4825
spam     747
Name: count, dtype: int64

In [70]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Category'] = le.fit_transform(df['Category'])

In [71]:
df.head()

   Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

In [72]:
X = df['Message']
y = df['Category']

In [73]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [74]:
vectorizer = TfidfVectorizer()

X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

In [75]:
model = MultinomialNB()

model.fit(X_train, y_train)

MultinomialNB()

In [76]:
y_pred = model.predict(X_test)

In [77]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.9650224215246637
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       966
           1       1.00      0.74      0.85       149

    accuracy                           0.97      1115
   macro avg       0.98      0.87      0.91      1115
weighted avg       0.97      0.97      0.96      1115

# for DF2

In [78]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18650 entries, 0 to 18649
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  18650 non-null  int64
 1   Email Text  18634 non-null  object
 2   Email Type  18650 non-null  object
dtypes: int64(1), object(2)
memory usage: 437.2+ KB

In [79]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [80]:
df2.shape

(18650, 3)

In [81]:
print(df2['Email Type'].value_counts())

Email Type
Safe Email        11322
Phishing Email     7328
Name: count, dtype: int64

In [82]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df2['Email Type'] = le.fit_transform(df2['Email Type'])

In [83]:
df2.head()

   Unnamed: 0                                         Email Text  Email Type
0           0  re : 6 . 1100 , disc : uniformitarianism , re ...           1
1           1  the other side of * galicismos * * galicismo *...           1
2           2  re : equistar deal tickets are you still avail...           1
3           3  \nHello I am your hot lil horny toy.\n    I am...           0
4           4  software at incredibly low prices ( 86 % lower...           0

In [84]:
df2 = df2.drop(df2.columns[0], axis=1)

In [85]:
df2.head()

                                          Email Text  Email Type
0  re : 6 . 1100 , disc : uniformitarianism , re ...           1
1  the other side of * galicismos * * galicismo *...           1
2  re : equistar deal tickets are you still avail...           1
3  \nHello I am your hot lil horny toy.\n    I am...           0
4  software at incredibly low prices ( 86 % lower...           0

In [92]:
df2["Email Text"] = df2["Email Text"].fillna("")

In [93]:
X = df2['Email Text']
y = df2['Email Type']

In [94]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [95]:
vectorizer = TfidfVectorizer()

X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

In [96]:
model = MultinomialNB()

model.fit(X_train, y_train)

MultinomialNB()

In [97]:
y_pred = model.predict(X_test)

In [98]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.8983914209115281
              precision    recall  f1-score   support

           0       0.97      0.76      0.85      1457
           1       0.87      0.98      0.92      2273

    accuracy                           0.90      3730
   macro avg       0.92      0.87      0.89      3730
weighted avg       0.91      0.90      0.90      3730